# Generated by Django 3.0.6 on 2020-05-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
