# Generated by Django 3.0.6 on 2020-06-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200604_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shippiing',
            new_name='Shipping',
        ),
    ]
