# Generated by Django 3.0.6 on 2020-06-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_customer_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
