# Generated by Django 3.0.6 on 2020-06-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
