# Generated by Django 3.0.6 on 2020-06-10 16:02

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='county',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
