# Generated by Django 3.0.6 on 2020-06-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Orderitem_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6),
        ),
    ]
