# Generated by Django 3.0.6 on 2020-06-13 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_orderitem_orderitem_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Orderitem_total',
            new_name='orderitem_total',
        ),
    ]
