# Generated by Django 3.0.6 on 2020-06-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20200613_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='member_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
