# Generated by Django 3.0.6 on 2020-06-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condtion',
            field=models.CharField(choices=[('brand new', 'Brand new'), ('Excellent', 'Excellent'), ('Mint', 'Mint'), ('Very good', 'Very good'), ('Good', 'Good')], default='', max_length=254),
        ),
    ]
