# Generated by Django 3.0.6 on 2020-06-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_product_condtion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='players_names',
            field=models.CharField(choices=[('Giggs', 'Giggs'), ('Schmeichel', 'Schmeichel'), ('Beckham', 'Beckham'), ('C Ronaldo', 'C Ronaldo'), ('Cantona', 'Cantona'), ('Rooney', 'Rooney'), ('Keane', 'Keane'), ('Scholes', 'Scholes')], default='', max_length=254),
        ),
    ]
