# Generated by Django 3.0.6 on 2020-06-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20200623_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='member_discount',
        ),
    ]
