# Generated by Django 3.0.6 on 2020-05-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourm', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
