# Generated by Django 3.0.6 on 2020-06-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourm', '0005_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
